### ISSUE TITLE
error executing user code in old 2.13-database

### ISSUE THREAD

**Issue by Hoffenbar** [wduquette/notebook#1]
Just noticed that there are internal differences between v2.13 and v2.20 regarding the commands which can be used in user-code:

invalid command name "showpage"
    while executing
"showpage Home"
    invoked from within
"::dbmanagerType::notebookdb7.interp eval {showpage Home}"
    ("uplevel" body line 1)
    invoked from within
"uplevel $self.interp eval $args"
    (procedure "::notebookdb::notebookdb::Snit_methodeval" line 6)
    invoked from within
"$db eval $script"
    (procedure "::notebookbrowser::Snit_methodEvalUserCode" line 11)
    invoked from within
"$self EvalUserCode $script"

So: Is there a "best way" to migrate an existing databases without the need of cut+pasting too much....?

**Comment by bttrx** [comment]
Hi!

According to Notebook's release notes "showpage" has been removed in version 2.1.3 being already deprecated in version 2.1.2.

To fix your problem you could try to open your NBK file with a plain-text editor, e. g., Notepad++ on Windows, and search & replace "showpage" by "goto-page", although I'm not sure, what "showpage" did exactly in the past.

Regards,
Robert

**Comment by Hoffenbar** [comment]
Hello,

many thanks - it works!!
Great!
