### ISSUE TITLE
Make me admin

### ISSUE THREAD

**Issue by bttrx** [wduquette/notebook#2]
Hi Will,

would you mind making me an admin for this project?
Currently I just want to close issue #1.
Later maybe I will try to continue Notebook development (on a minor level).

Cheers,
Robert

**Comment by wduquette** [comment]
You should receive a collaboration request; accept it and then I'll set up privs.

**Comment by bttrx** [comment]
I got it and accepted it. Thanks.

**Comment by bttrx** [comment]
I closed issue #1 now. So it works.
